<a href="https://colab.research.google.com/github/Ilyasmbt/deep_learning/blob/main/TENSOR%2CKERAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# creating tensors


In [ ]:
scalar,matrix,vector,tensor

In [5]:
import tensorflow as tf

a=tf.constant(3)
b=tf.constant([1.0,2.0,3.0])
c=tf.constant([[1.0,2.0],[3.0,4.0]])
print("constant a:",a)
print("constant b:",b)
print("constant c:",c)

v=tf.Variable([1.0,2.0,3.0])
print("variable v:",v)

r=tf.random.normal([3,3], mean=0.0, stddev=1.0)
print("random tensor r:",r)

constant a: tf.Tensor(3, shape=(), dtype=int32)
constant b: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
constant c: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
variable v: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
random tensor r: tf.Tensor(
[[ 2.1773214   0.6244376   1.0137291 ]
 [ 0.9316394  -0.01413546  0.23167126]
 [-0.7793717   2.1560874  -0.134206  ]], shape=(3, 3), dtype=float32)


# 2 basic operation


In [6]:
import tensorflow as tf

x=tf.constant([1,2,3])
y=tf.constant([4,5,6])

add_result= x +y
mul_result= x *y

print("addition:",add_result.numpy())
print("multiplication:",mul_result.numpy())

matrix1=tf.constant([[1,2],[3,4]])
matrix2=tf.constant([[5,6],[7,8]])

matrix_multiplication_result=tf.matmul(matrix1,matrix2)
matrix_transpose_result=tf.transpose(matrix1)

print("matrix multiplication:",matrix_multiplication_result.numpy())
print("matrix transpose:",matrix_transpose_result.numpy())




addition: [5 7 9]
multiplication: [ 4 10 18]
matrix multiplication: [[19 22]
 [43 50]]
matrix transpose: [[1 3]
 [2 4]]


# 3 Reshaping and Slicing

In [7]:
import tensorflow as tf

tensor1=tf.constant([1,2,3,4,5,6,7,8,9])
tensor2=tf.constant([[1,2,3],[4,5,6]])
reshaped_tensor=tf.reshape(tensor1,(3,3))    #reshape to 3 rows ,3 columns

print("original tensor: \n",tensor1.numpy())
print("reshaped tensor (3x3): \n",reshaped_tensor.numpy())

tensor1_slice= tensor2[:,1]
print("slicing tensor1:\n",tensor1_slice.numpy())


original tensor: 
 [1 2 3 4 5 6 7 8 9]
reshaped tensor (3x3): 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
slicing tensor1:
 [2 5]


# 4 broadcasting

In [8]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant(2)

c=a+b   # b is broadcast to [2,2,2]

print("TENSOR a:",a.numpy())
print("tensor b:",b.numpy())
print("broadcasting result:\n",c.numpy())

TENSOR a: [1 2 3]
tensor b: 2
broadcasting result:
 [3 4 5]


# basic operations in keras

layer creating tool

importing keras modules

In [9]:
#importing keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D ,Flatten, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.metrics import Accuracy

In [10]:
#step1 creating the sequential model
model=Sequential()

#step2: add layers to the model
#add a hidden dense layer with 64 units and Relu Activation
model.add(Dense(64,activation="relu"))

#add an output layer with 1 unit and sigmoid activation for binary classification

model.add(Dense(1,activation="sigmoid"))

In [11]:
model.compile(optimizer=Adam(),
              loss="binary_crossentropy",
              metrics=["accuracy"])

In [13]:
#generate dumy training data

import numpy as np

x_train= np.random.random((1000,20))
y_train=np.random.randint(2,size=(1000,1))

#train the model
model.fit(x_train,y_train,epochs=10, batch_size=32)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5155 - loss: 0.6952 
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5146 - loss: 0.6959
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5437 - loss: 0.6889
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5296 - loss: 0.6889
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5482 - loss: 0.6881
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5497 - loss: 0.6856
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5666 - loss: 0.6825
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5475 - loss: 0.6827
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5530 - loss: 0.6879
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5817 - loss: 0.6794


In [14]:
#test
x_test=np.random.random((100,20))
y_test=np.random.randint(2,size=(100,1))

loss , accuracy = model.evaluate(x_test,y_test)
print("Test loss:",loss)
print("Test accuracy:",accuracy)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5266 - loss: 0.6937 
Test loss: 0.6955958604812622
Test accuracy: 0.5299999713897705


In [15]:
x_new =np.random.random((10,20))    #10 new sample,each with 20 features
predictions = model.predict(x_new)    # get model predictions

print("predictions:\n",predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step
predictions:
 [[0.5912606 ]
 [0.5148782 ]
 [0.569538  ]
 [0.6012288 ]
 [0.535918  ]
 [0.49873585]
 [0.58637714]
 [0.59554416]
 [0.55007136]
 [0.49732184]]
